### ISSUE TITLE
Mercedes-Benz SL65 Engine Sound

### ISSUE THREAD

**Issue by nutrient10** [FredyH/Perpheads-Issues#867]
After the most recent update, most of the engine sounds for the Mercedes SL65 don't work.
The start-up sound and the idle sound seem to work but no other engine sounds do.

**Comment by TinySimon** [comment]
fixed

**Comment by nutrient10** [comment]
Apparently, this isn't fixed, for this vehicle at least

**Comment by nutrient10** [comment]
Unsure about other cars, but the engine sounds for the Mercedes SL65 are still missing (RTU and civilian one)

**Comment by TinySimon** [comment]
Is your content pack updated? I'm not having any issues with this car.

**Comment by nutrient10** [comment]
It's possible but someone else had the same problem, I'll make sure everything is up to date and have another look
