### ISSUE TITLE
DNA Tool Lua Error

### ISSUE THREAD

**Issue by R-Flexx** [FredyH/Perpheads-Issues#899]
Happens when a body has been killed via fire and sometimes when they just get shot.

```
[ERROR] lua/includes/extensions/table.lua:158: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Count - lua/includes/extensions/table.lua:158
    3. processDNA - gamemodes/perp/gamemode/modules/jobs/medic/cl_dnasampler.lua:143
     4. unknown - gamemodes/perp/gamemode/modules/jobs/medic/cl_dnasampler.lua:168

```

**Comment by TinySimon** [comment]
Fixed

**Comment by R-Flexx** [comment]
it still happens. It occurs when dna has disappeared from a body and only the victim can be identified

**Comment by nutrient10** [comment]
I'm pretty sure this is gonna be fixed on restart. Not immediately.
